In [8]:
import pandas as pd

In [2]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s=pd.Series([100,200,300],
            index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [5]:
data={'maths':89,
     'physics':90,
     'chemistry':83
    }
s=pd.Series(data)
print(s)

maths        89
physics      90
chemistry    83
dtype: int64

In [6]:
s=pd.Series([10,20,30,40])
print(s[2])

30

In [8]:
s=pd.Series([100,200,300],index=['A','B','C'])
print(s['B'])

200

In [10]:
s=pd.Series([100,200,300],index=['A','B','C'])
print(s[['A','B']])

A    100
B    200
dtype: int64

In [11]:
print(s.size)

3

In [12]:
print(s.shape)

(3,)

In [14]:
print(s.dtype)

int64

In [15]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [17]:
print(s*5)

0     50
1    100
2    150
3    200
dtype: int64

In [18]:
print("sum=",s.sum())
print("mean=",s.mean())
print("minimum=",s.min())
print("maximum=",s.max())

sum= 100
mean= 25.0
minimum= 10
maximum= 40

In [17]:
data={"roll number":[101,102,103,104,105,],
      "name":["arun","priya","rahul","vaish","vijay"],
      "marks":[78,99,87,78,90]
     }
df=pd.DataFrame(data)
print(df)

   roll number   name  marks
0          101   arun     78
1          102  priya     99
2          103  rahul     87
3          104  vaish     78
4          105  vijay     90

In [11]:
df=pd.DataFrame(data,
                index=['A','B','C'])
print(df)

   roll number   name  marks
A          101   arun     78
B          102  priya     99
C          103  rahul     87

In [11]:
print(df.columns)

Index(['roll number', 'name', 'marks'], dtype='object')

In [12]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')

In [13]:
print(df.dtypes)

roll number     int64
name           object
marks           int64
dtype: object

In [14]:
print(df[['name','marks']])

    name  marks
A   arun     78
B  priya     99
C  rahul     87

In [15]:
print(df['name'])

A     arun
B    priya
C    rahul
Name: name, dtype: object

In [19]:
print(df.loc[0])

roll number     101
name           arun
marks            78
Name: 0, dtype: object

In [20]:
print(df.loc[[0,2]])

   roll number   name  marks
0          101   arun     78
2          103  rahul     87

In [21]:
print(df.iloc[1])

roll number      102
name           priya
marks             99
Name: 1, dtype: object

In [22]:
print(df.iloc[[0,2]])

   roll number   name  marks
0          101   arun     78
2          103  rahul     87

In [23]:
print(df.iloc[0:2,1:3])

    name  marks
0   arun     78
1  priya     99

In [39]:
df['grade']=['A','A+','B']
print(df)

   roll number   name  marks grade
0          101   arun     78     A
1          102  priya     99    A+
2          103  rahul     87     B

In [30]:
df['marks']=df['marks']+5
print(df)

   roll number   name  marks
0          101   arun     88
1          102  priya    109
2          103  rahul     97

In [41]:
df.drop('grade',
        axis=1,
        inplace=True)
print(df)

   roll number   name  marks
0          101   arun     78
1          102  priya     99
2          103  rahul     87

In [43]:
print(df['marks'].sum())

264

In [44]:
print(df['marks'].mean())

88.0

In [45]:
print(df['marks'].max())

99

In [46]:
print(df['marks'].min())

78

In [47]:
df.sort_values('marks')

   roll number   name  marks
0          101   arun     78
2          103  rahul     87
1          102  priya     99

In [49]:
df.sort_values('marks',ascending=False)

   roll number   name  marks
1          102  priya     99
2          103  rahul     87
0          101   arun     78

In [12]:
print(df[df['marks']>80])

   roll number   name  marks
B          102  priya     99
C          103  rahul     87

In [13]:
print(df[df['marks']<90])

   roll number   name  marks
A          101   arun     78
C          103  rahul     87

In [18]:
df.head()

   roll number   name  marks
0          101   arun     78
1          102  priya     99
2          103  rahul     87
3          104  vaish     78
4          105  vijay     90

In [19]:
df.tail()

   roll number   name  marks
0          101   arun     78
1          102  priya     99
2          103  rahul     87
3          104  vaish     78
4          105  vijay     90

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   roll number  5 non-null      int64
 1   name         5 non-null      object
 2   marks        5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [29]:
data={"roll number":[1,2,3,4,5,6,],
      "name":["arun","priya","rahul","vaish","vijay","rishi"],
      "department":["cs","ai","bca","mech","bcom","bba"],
      "cgpa":[7.7,9.6,6,9.9,7,7.8],
      "marks":[79,98,67,99,70,89]
     }
df=pd.DataFrame(data)
print(df)

   roll number   name department  cgpa  marks
0            1   arun         cs   7.7     79
1            2  priya         ai   9.6     98
2            3  rahul        bca   6.0     67
3            4  vaish       mech   9.9     99
4            5  vijay       bcom   7.0     70
5            6  rishi        bba   7.8     89

In [31]:
print(df["marks"].sum())

502

In [32]:
print(df["marks"].mean())

83.66666666666667

In [33]:
print(df["marks"].min())

67

In [34]:
print(df["marks"].max())

99